import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/component/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'まっけのぶろぐ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <main className='bg-blue-100'>
          <div className="container mx-auto">{children}</div>
        </main>
      </body>
    </html>
  )
}
